services:
  db:
    image: postgres:16
    container_name: commitment-tracker-db
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    network_mode: "host"

volumes:
  db-data:
