version: "3"

dotenv:
  - .env.local
  - ".env"

interval: "500ms"

vars:
  PATH_CHARM: "./charm/charm_amd64.charm"
  IMAGE: "specs.canonical.com:latest"
  APP_NAME: "specs"
  ROCK: "canonical-specs-v2_2.0.0_amd64.rock"

tasks:
  install_bun:
    description: "Install bun"
    status:
      - which bun
    cmds:
      - echo "Installing bun..."
      - curl -fsSL https://bun.sh/install | bash

  tools:
    description: "Install tools"
    deps: ["install_bun"]
    cmds:
      - echo "Installing tools..."
      - go install github.com/mitranim/gow@af11a6e
      - go install github.com/gzuidhof/tygo@v0.2.17

  build:
    description: "Build the application"
    deps: ["tools", "build_ui"]
    cmds:
      - echo "Building the application..."
      - go build -o bin/api cmd/api/main.go
      - go build -o bin/sync cmd/sync/main.go
      - go build -o bin/migrate cmd/migrate/main.go
      - go build -o bin/reject cmd/reject/main.go

  run:
    description: "Run the application"
    deps: ["tools", "build"]
    cmds:
      - go run cmd/api/main.go

  run_sync:
    description: "Run the application in synchronous mode"
    deps: ["tools", "build"]
    cmds:
      - go run cmd/sync/main.go

  run_reject:
    description: "Run the rejection worker"
    deps: ["tools", "build"]
    cmds:
      - go run cmd/reject/main.go --dry-run --google-doc-id={{.DOC_ID}}
    vars:
      DOC_ID: '{{default "" .DOC_ID}}'

  dev:
    description: "Run the application in watch mode"
    deps: ["tools", "build"]
    cmds:
      - gow -r=false -e=go,mod,html,js,css run cmd/api/main.go & cd ui && bun dev

  migrate:
    description: "Run the migrations"
    deps: ["tools"]
    cmds:
      - go run cmd/migrate/main.go

  ### UI tasks
  generate_types:
    description: "Generate types"
    deps: ["tools"]
    cmds:
      - echo "Generating types..."
      - tygo generate --config ./tygo.yaml

  build_ui:
    description: "Build the UI"
    deps: ["tools"]
    status:
      - test -d ui/dist
    cmds:
      - task: rebuild_ui


  rebuild_ui:
    description: "Re-build the UI"
    deps: [ "tools" ]
    cmds:
      - echo "Building the UI..."
      - cd ui && bun install  && bun run build

  # Juju tasks
  clean-imgs:
    desc: Clean all local images
    cmds:
      - microk8s ctr images list | grep 'localhost:32000/specs' | awk '{print $1}' | xargs -r microk8s ctr images remove
  load-img:
    desc: Load .rock image into local registry
    cmds:
      - rockcraft.skopeo --insecure-policy copy --dest-tls-verify=false oci-archive:{{.ROCK}} docker://localhost:32000/{{.IMAGE}}
  deploy:
    desc: Deploy the charm to microk8s
    cmds:
      - juju deploy {{.PATH_CHARM}} {{.APP_NAME}} --resource app-image=localhost:32000/{{.IMAGE}}
  refresh:
    desc: Refresh the charm in microk8s
    cmds:
      - juju refresh {{.APP_NAME}} --path {{.PATH_CHARM}} --resource app-image=localhost:32000/{{.IMAGE}}
  ssh:
    desc: SSH into the worker container
    cmds:
      - juju ssh --container app {{.APP_NAME}}/0 bash
